### ISSUE TITLE
Possibility to set cloudAgentKey from secret

### ISSUE THREAD

**Issue by Hronom** [kubecost/kubecost-cloud-agent#19]
In [guideline here](https://docs.kubecost.com/kubecost-cloud/cloud-installation-and-onboarding#agent-install) you have description on setting `` through parameters.

The way how chart formed - it's not possible to set it through env variable from secret.

Please add this possibility

**Comment by teevans** [comment]
@Hronom - This should be added! Please let us know if you have any questions! Closing for now.

**Comment by cliffcolvin** [comment]
@Hronom I just linked #15 here, does this solve your ask?

**Comment by teevans** [comment]
@Hronom - It looks like the PR above adds the functionality! Closing for now, please let us know if you have any questions!
